export type Trait =
  | 'Amphibious'
  | 'Bred for war'
  | 'Brutal'
  | 'Courageous'
  | 'Eternal'
  | 'Frenzy'
  | 'Horrify'
  | 'Martial'
  | 'Mindless'
  | 'Regenerate'
  | 'Ravenous'
  | 'Rock-hurler'
  | 'Savage'
  | 'Stalwart'
  | 'Twisting Roots'
  | 'Undead'
  | 'Charge'
  | 'Always Diminished';
